require("ivan.plugins-setup")
require("ivan.core.options")
require("ivan.core.keymaps")
require("ivan.core.colorscheme")

require("ivan.plugins.comment")
require("ivan.plugins.nvim-tree")
require("ivan.plugins.lualine")
require("ivan.plugins.bufferline")
require("ivan.plugins.telescope")
require("ivan.plugins.nvim-cmp")
require("ivan.plugins.lsp.mason")
require("ivan.plugins.lsp.lspsaga")
require("ivan.plugins.lsp.lspconfig")
require("ivan.plugins.lsp.null-ls")
require("ivan.plugins.autopairs")
require("ivan.plugins.treesitter")
require("ivan.plugins.gitsigns")
